// Code generated by protoc-gen-go. DO NOT EDIT.
// source: algorithm.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Algorithm struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Algorithm) Reset()         { *m = Algorithm{} }
func (m *Algorithm) String() string { return proto.CompactTextString(m) }
func (*Algorithm) ProtoMessage()    {}
func (*Algorithm) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{0}
}

func (m *Algorithm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Algorithm.Unmarshal(m, b)
}
func (m *Algorithm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Algorithm.Marshal(b, m, deterministic)
}
func (m *Algorithm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Algorithm.Merge(m, src)
}
func (m *Algorithm) XXX_Size() int {
	return xxx_messageInfo_Algorithm.Size(m)
}
func (m *Algorithm) XXX_DiscardUnknown() {
	xxx_messageInfo_Algorithm.DiscardUnknown(m)
}

var xxx_messageInfo_Algorithm proto.InternalMessageInfo

func (m *Algorithm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Algorithm) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type CreateAlgorithmCommand struct {
	Algorithm            *Algorithm                             `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	CreatedOn            int64                                  `protobuf:"varint,2,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	Files                []*CreateAlgorithmCommandAlgorithmFile `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	Id                   string                                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *CreateAlgorithmCommand) Reset()         { *m = CreateAlgorithmCommand{} }
func (m *CreateAlgorithmCommand) String() string { return proto.CompactTextString(m) }
func (*CreateAlgorithmCommand) ProtoMessage()    {}
func (*CreateAlgorithmCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{1}
}

func (m *CreateAlgorithmCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlgorithmCommand.Unmarshal(m, b)
}
func (m *CreateAlgorithmCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlgorithmCommand.Marshal(b, m, deterministic)
}
func (m *CreateAlgorithmCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlgorithmCommand.Merge(m, src)
}
func (m *CreateAlgorithmCommand) XXX_Size() int {
	return xxx_messageInfo_CreateAlgorithmCommand.Size(m)
}
func (m *CreateAlgorithmCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlgorithmCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlgorithmCommand proto.InternalMessageInfo

func (m *CreateAlgorithmCommand) GetAlgorithm() *Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return nil
}

func (m *CreateAlgorithmCommand) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *CreateAlgorithmCommand) GetFiles() []*CreateAlgorithmCommandAlgorithmFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *CreateAlgorithmCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateAlgorithmCommandAlgorithmFile struct {
	FileType             string   `protobuf:"bytes,1,opt,name=fileType,proto3" json:"fileType,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAlgorithmCommandAlgorithmFile) Reset()         { *m = CreateAlgorithmCommandAlgorithmFile{} }
func (m *CreateAlgorithmCommandAlgorithmFile) String() string { return proto.CompactTextString(m) }
func (*CreateAlgorithmCommandAlgorithmFile) ProtoMessage()    {}
func (*CreateAlgorithmCommandAlgorithmFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{1, 0}
}

func (m *CreateAlgorithmCommandAlgorithmFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlgorithmCommandAlgorithmFile.Unmarshal(m, b)
}
func (m *CreateAlgorithmCommandAlgorithmFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlgorithmCommandAlgorithmFile.Marshal(b, m, deterministic)
}
func (m *CreateAlgorithmCommandAlgorithmFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlgorithmCommandAlgorithmFile.Merge(m, src)
}
func (m *CreateAlgorithmCommandAlgorithmFile) XXX_Size() int {
	return xxx_messageInfo_CreateAlgorithmCommandAlgorithmFile.Size(m)
}
func (m *CreateAlgorithmCommandAlgorithmFile) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlgorithmCommandAlgorithmFile.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlgorithmCommandAlgorithmFile proto.InternalMessageInfo

func (m *CreateAlgorithmCommandAlgorithmFile) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *CreateAlgorithmCommandAlgorithmFile) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type AlgorithmCreatedCommand struct {
	Algorithm            *Algorithm `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Id                   string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AlgorithmCreatedCommand) Reset()         { *m = AlgorithmCreatedCommand{} }
func (m *AlgorithmCreatedCommand) String() string { return proto.CompactTextString(m) }
func (*AlgorithmCreatedCommand) ProtoMessage()    {}
func (*AlgorithmCreatedCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{2}
}

func (m *AlgorithmCreatedCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlgorithmCreatedCommand.Unmarshal(m, b)
}
func (m *AlgorithmCreatedCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlgorithmCreatedCommand.Marshal(b, m, deterministic)
}
func (m *AlgorithmCreatedCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlgorithmCreatedCommand.Merge(m, src)
}
func (m *AlgorithmCreatedCommand) XXX_Size() int {
	return xxx_messageInfo_AlgorithmCreatedCommand.Size(m)
}
func (m *AlgorithmCreatedCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AlgorithmCreatedCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AlgorithmCreatedCommand proto.InternalMessageInfo

func (m *AlgorithmCreatedCommand) GetAlgorithm() *Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return nil
}

func (m *AlgorithmCreatedCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AlgorithmAssociatedWithDSCommand struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlgorithmAssociatedWithDSCommand) Reset()         { *m = AlgorithmAssociatedWithDSCommand{} }
func (m *AlgorithmAssociatedWithDSCommand) String() string { return proto.CompactTextString(m) }
func (*AlgorithmAssociatedWithDSCommand) ProtoMessage()    {}
func (*AlgorithmAssociatedWithDSCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{3}
}

func (m *AlgorithmAssociatedWithDSCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlgorithmAssociatedWithDSCommand.Unmarshal(m, b)
}
func (m *AlgorithmAssociatedWithDSCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlgorithmAssociatedWithDSCommand.Marshal(b, m, deterministic)
}
func (m *AlgorithmAssociatedWithDSCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlgorithmAssociatedWithDSCommand.Merge(m, src)
}
func (m *AlgorithmAssociatedWithDSCommand) XXX_Size() int {
	return xxx_messageInfo_AlgorithmAssociatedWithDSCommand.Size(m)
}
func (m *AlgorithmAssociatedWithDSCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AlgorithmAssociatedWithDSCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AlgorithmAssociatedWithDSCommand proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Algorithm)(nil), "pb.Algorithm")
	proto.RegisterType((*CreateAlgorithmCommand)(nil), "pb.CreateAlgorithmCommand")
	proto.RegisterType((*CreateAlgorithmCommandAlgorithmFile)(nil), "pb.CreateAlgorithmCommand.algorithmFile")
	proto.RegisterType((*AlgorithmCreatedCommand)(nil), "pb.AlgorithmCreatedCommand")
	proto.RegisterType((*AlgorithmAssociatedWithDSCommand)(nil), "pb.AlgorithmAssociatedWithDSCommand")
}

func init() { proto.RegisterFile("algorithm.proto", fileDescriptor_8c381a4f1e580eed) }

var fileDescriptor_8c381a4f1e580eed = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x69, 0xba, 0xfe, 0xe9, 0x2c, 0xab, 0x30, 0x07, 0x0d, 0x8b, 0x87, 0x92, 0x53, 0x41,
	0xe8, 0x61, 0x3d, 0x79, 0x11, 0x96, 0x15, 0xbd, 0x29, 0x54, 0xd1, 0x73, 0xbb, 0x8d, 0x76, 0xa0,
	0x6d, 0x4a, 0x5b, 0x04, 0xbf, 0xbb, 0x07, 0x49, 0x62, 0x12, 0x04, 0x4f, 0xde, 0x32, 0x33, 0x2f,
	0xbf, 0xf7, 0x26, 0x81, 0xd3, 0xb2, 0x7d, 0x57, 0x23, 0xcd, 0x4d, 0x97, 0x0f, 0xa3, 0x9a, 0x15,
	0xb2, 0xa1, 0x12, 0xd7, 0x90, 0x6c, 0x5d, 0x1b, 0x11, 0x16, 0x7d, 0xd9, 0x49, 0x1e, 0xa5, 0x51,
	0x96, 0x14, 0xe6, 0x8c, 0x1c, 0x8e, 0x3e, 0xe4, 0x38, 0x91, 0xea, 0x39, 0x33, 0x6d, 0x57, 0x8a,
	0xaf, 0x08, 0xce, 0x76, 0xa3, 0x2c, 0x67, 0xe9, 0x09, 0x3b, 0xd5, 0x75, 0x65, 0x5f, 0xe3, 0x25,
	0x24, 0xde, 0xcc, 0xd0, 0x96, 0x9b, 0x55, 0x3e, 0x54, 0xb9, 0x17, 0x16, 0x61, 0x8e, 0x17, 0x90,
	0xec, 0x0d, 0xa6, 0x7e, 0xb4, 0x1e, 0x71, 0x11, 0x1a, 0x78, 0x03, 0x07, 0x6f, 0xd4, 0xca, 0x89,
	0xc7, 0x69, 0x9c, 0x2d, 0x37, 0x99, 0xc6, 0xfc, 0xed, 0x9a, 0x7b, 0xe4, 0x1d, 0xb5, 0xb2, 0xb0,
	0xd7, 0xf0, 0x04, 0x18, 0xd5, 0x7c, 0x61, 0xa2, 0x33, 0xaa, 0xd7, 0xf7, 0xb0, 0xfa, 0xa5, 0xc3,
	0x35, 0x1c, 0x6b, 0xe5, 0xf3, 0xe7, 0xe0, 0x16, 0xf7, 0xb5, 0x9b, 0x3d, 0xe8, 0x47, 0x61, 0x61,
	0xa6, 0x6b, 0xf1, 0x02, 0xe7, 0x21, 0x81, 0x8d, 0xfb, 0xaf, 0xf5, 0x6d, 0x40, 0xe6, 0x02, 0x0a,
	0x01, 0xa9, 0xd7, 0x6d, 0xa7, 0x49, 0xed, 0x49, 0xa3, 0x5f, 0x69, 0x6e, 0x6e, 0x9f, 0x7e, 0x0c,
	0xaa, 0x43, 0xf3, 0x81, 0x57, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xeb, 0x28, 0x63, 0xd3,
	0x01, 0x00, 0x00,
}
