// Code generated by protoc-gen-go. DO NOT EDIT.
// source: algorithm.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateAlgorithmCommand struct {
	Algorithm            *Algorithm `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	CreatedOn            int64      `protobuf:"varint,2,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	Id                   string     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateAlgorithmCommand) Reset()         { *m = CreateAlgorithmCommand{} }
func (m *CreateAlgorithmCommand) String() string { return proto.CompactTextString(m) }
func (*CreateAlgorithmCommand) ProtoMessage()    {}
func (*CreateAlgorithmCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{0}
}

func (m *CreateAlgorithmCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlgorithmCommand.Unmarshal(m, b)
}
func (m *CreateAlgorithmCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlgorithmCommand.Marshal(b, m, deterministic)
}
func (m *CreateAlgorithmCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlgorithmCommand.Merge(m, src)
}
func (m *CreateAlgorithmCommand) XXX_Size() int {
	return xxx_messageInfo_CreateAlgorithmCommand.Size(m)
}
func (m *CreateAlgorithmCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlgorithmCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlgorithmCommand proto.InternalMessageInfo

func (m *CreateAlgorithmCommand) GetAlgorithm() *Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return nil
}

func (m *CreateAlgorithmCommand) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *CreateAlgorithmCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AssociateFileCommand struct {
	Algorithm            *Algorithm     `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	AlgorithmFile        *AlgorithmFile `protobuf:"bytes,2,opt,name=algorithmFile,proto3" json:"algorithmFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AssociateFileCommand) Reset()         { *m = AssociateFileCommand{} }
func (m *AssociateFileCommand) String() string { return proto.CompactTextString(m) }
func (*AssociateFileCommand) ProtoMessage()    {}
func (*AssociateFileCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{1}
}

func (m *AssociateFileCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssociateFileCommand.Unmarshal(m, b)
}
func (m *AssociateFileCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssociateFileCommand.Marshal(b, m, deterministic)
}
func (m *AssociateFileCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssociateFileCommand.Merge(m, src)
}
func (m *AssociateFileCommand) XXX_Size() int {
	return xxx_messageInfo_AssociateFileCommand.Size(m)
}
func (m *AssociateFileCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AssociateFileCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AssociateFileCommand proto.InternalMessageInfo

func (m *AssociateFileCommand) GetAlgorithm() *Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return nil
}

func (m *AssociateFileCommand) GetAlgorithmFile() *AlgorithmFile {
	if m != nil {
		return m.AlgorithmFile
	}
	return nil
}

type GetAlgorithmQuery struct {
	Algorithm            *Algorithm `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	CreatedOn            int64      `protobuf:"varint,2,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	Id                   string     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAlgorithmQuery) Reset()         { *m = GetAlgorithmQuery{} }
func (m *GetAlgorithmQuery) String() string { return proto.CompactTextString(m) }
func (*GetAlgorithmQuery) ProtoMessage()    {}
func (*GetAlgorithmQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{2}
}

func (m *GetAlgorithmQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlgorithmQuery.Unmarshal(m, b)
}
func (m *GetAlgorithmQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlgorithmQuery.Marshal(b, m, deterministic)
}
func (m *GetAlgorithmQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlgorithmQuery.Merge(m, src)
}
func (m *GetAlgorithmQuery) XXX_Size() int {
	return xxx_messageInfo_GetAlgorithmQuery.Size(m)
}
func (m *GetAlgorithmQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlgorithmQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlgorithmQuery proto.InternalMessageInfo

func (m *GetAlgorithmQuery) GetAlgorithm() *Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return nil
}

func (m *GetAlgorithmQuery) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *GetAlgorithmQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Algorithm struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	FileIDs              []string `protobuf:"bytes,5,rep,name=fileIDs,proto3" json:"fileIDs,omitempty"`
	DatasetIDs           []string `protobuf:"bytes,6,rep,name=datasetIDs,proto3" json:"datasetIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Algorithm) Reset()         { *m = Algorithm{} }
func (m *Algorithm) String() string { return proto.CompactTextString(m) }
func (*Algorithm) ProtoMessage()    {}
func (*Algorithm) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{3}
}

func (m *Algorithm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Algorithm.Unmarshal(m, b)
}
func (m *Algorithm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Algorithm.Marshal(b, m, deterministic)
}
func (m *Algorithm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Algorithm.Merge(m, src)
}
func (m *Algorithm) XXX_Size() int {
	return xxx_messageInfo_Algorithm.Size(m)
}
func (m *Algorithm) XXX_DiscardUnknown() {
	xxx_messageInfo_Algorithm.DiscardUnknown(m)
}

var xxx_messageInfo_Algorithm proto.InternalMessageInfo

func (m *Algorithm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Algorithm) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Algorithm) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Algorithm) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Algorithm) GetFileIDs() []string {
	if m != nil {
		return m.FileIDs
	}
	return nil
}

func (m *Algorithm) GetDatasetIDs() []string {
	if m != nil {
		return m.DatasetIDs
	}
	return nil
}

type AlgorithmFile struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Filetype             string   `protobuf:"bytes,3,opt,name=filetype,proto3" json:"filetype,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlgorithmFile) Reset()         { *m = AlgorithmFile{} }
func (m *AlgorithmFile) String() string { return proto.CompactTextString(m) }
func (*AlgorithmFile) ProtoMessage()    {}
func (*AlgorithmFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{4}
}

func (m *AlgorithmFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlgorithmFile.Unmarshal(m, b)
}
func (m *AlgorithmFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlgorithmFile.Marshal(b, m, deterministic)
}
func (m *AlgorithmFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlgorithmFile.Merge(m, src)
}
func (m *AlgorithmFile) XXX_Size() int {
	return xxx_messageInfo_AlgorithmFile.Size(m)
}
func (m *AlgorithmFile) XXX_DiscardUnknown() {
	xxx_messageInfo_AlgorithmFile.DiscardUnknown(m)
}

var xxx_messageInfo_AlgorithmFile proto.InternalMessageInfo

func (m *AlgorithmFile) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *AlgorithmFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AlgorithmFile) GetFiletype() string {
	if m != nil {
		return m.Filetype
	}
	return ""
}

func (m *AlgorithmFile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Events
type AlgorithmCreatedEvent struct {
	Algorithm            *Algorithm `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Id                   string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AlgorithmCreatedEvent) Reset()         { *m = AlgorithmCreatedEvent{} }
func (m *AlgorithmCreatedEvent) String() string { return proto.CompactTextString(m) }
func (*AlgorithmCreatedEvent) ProtoMessage()    {}
func (*AlgorithmCreatedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{5}
}

func (m *AlgorithmCreatedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlgorithmCreatedEvent.Unmarshal(m, b)
}
func (m *AlgorithmCreatedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlgorithmCreatedEvent.Marshal(b, m, deterministic)
}
func (m *AlgorithmCreatedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlgorithmCreatedEvent.Merge(m, src)
}
func (m *AlgorithmCreatedEvent) XXX_Size() int {
	return xxx_messageInfo_AlgorithmCreatedEvent.Size(m)
}
func (m *AlgorithmCreatedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AlgorithmCreatedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AlgorithmCreatedEvent proto.InternalMessageInfo

func (m *AlgorithmCreatedEvent) GetAlgorithm() *Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return nil
}

func (m *AlgorithmCreatedEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MultipleAlgorithms struct {
	Algorithms           []*Algorithm `protobuf:"bytes,1,rep,name=algorithms,proto3" json:"algorithms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MultipleAlgorithms) Reset()         { *m = MultipleAlgorithms{} }
func (m *MultipleAlgorithms) String() string { return proto.CompactTextString(m) }
func (*MultipleAlgorithms) ProtoMessage()    {}
func (*MultipleAlgorithms) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{6}
}

func (m *MultipleAlgorithms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipleAlgorithms.Unmarshal(m, b)
}
func (m *MultipleAlgorithms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipleAlgorithms.Marshal(b, m, deterministic)
}
func (m *MultipleAlgorithms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipleAlgorithms.Merge(m, src)
}
func (m *MultipleAlgorithms) XXX_Size() int {
	return xxx_messageInfo_MultipleAlgorithms.Size(m)
}
func (m *MultipleAlgorithms) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipleAlgorithms.DiscardUnknown(m)
}

var xxx_messageInfo_MultipleAlgorithms proto.InternalMessageInfo

func (m *MultipleAlgorithms) GetAlgorithms() []*Algorithm {
	if m != nil {
		return m.Algorithms
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateAlgorithmCommand)(nil), "pb.CreateAlgorithmCommand")
	proto.RegisterType((*AssociateFileCommand)(nil), "pb.AssociateFileCommand")
	proto.RegisterType((*GetAlgorithmQuery)(nil), "pb.GetAlgorithmQuery")
	proto.RegisterType((*Algorithm)(nil), "pb.Algorithm")
	proto.RegisterType((*AlgorithmFile)(nil), "pb.AlgorithmFile")
	proto.RegisterType((*AlgorithmCreatedEvent)(nil), "pb.AlgorithmCreatedEvent")
	proto.RegisterType((*MultipleAlgorithms)(nil), "pb.MultipleAlgorithms")
}

func init() { proto.RegisterFile("algorithm.proto", fileDescriptor_8c381a4f1e580eed) }

var fileDescriptor_8c381a4f1e580eed = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0x6d, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x6f, 0xd3, 0x5a, 0xcd, 0x9c, 0xf1, 0xb8, 0xd1, 0x2b, 0x4b, 0x11, 0x09, 0x79, 0x55,
	0x10, 0x0b, 0x46, 0x50, 0xf1, 0x85, 0x50, 0xea, 0x03, 0xbe, 0x10, 0x31, 0xfa, 0x05, 0xb6, 0xcd,
	0x1a, 0x17, 0x92, 0x6c, 0xc8, 0x6e, 0x0f, 0x0e, 0xfc, 0x26, 0x7e, 0x0b, 0x3f, 0x85, 0x1f, 0x4b,
	0x76, 0x9b, 0x6e, 0x9e, 0x0e, 0x44, 0xe1, 0xde, 0x75, 0x76, 0xe6, 0xff, 0x9b, 0x7f, 0x87, 0x99,
	0xc0, 0x19, 0xcb, 0x33, 0x59, 0x0b, 0xfd, 0xbd, 0x58, 0x55, 0xb5, 0xd4, 0x12, 0xbd, 0x6a, 0x1b,
	0x29, 0x98, 0x6f, 0x6a, 0xce, 0x34, 0x5f, 0x1f, 0x93, 0x1b, 0x59, 0x14, 0xac, 0x4c, 0xf1, 0x31,
	0xf8, 0x4e, 0x40, 0x49, 0x48, 0x96, 0xa7, 0x71, 0xb0, 0xaa, 0xb6, 0x2b, 0x57, 0x98, 0xb4, 0x79,
	0x7c, 0x08, 0xfe, 0xce, 0x62, 0xd2, 0x4f, 0x25, 0xf5, 0x42, 0xb2, 0x9c, 0x24, 0xed, 0x03, 0xde,
	0x03, 0x4f, 0xa4, 0x74, 0x12, 0x92, 0xa5, 0x9f, 0x78, 0x22, 0x8d, 0x7e, 0xc0, 0x83, 0xb5, 0x52,
	0x72, 0x27, 0x98, 0xe6, 0xef, 0x44, 0xce, 0xff, 0xab, 0xe5, 0x0b, 0x08, 0x5c, 0x60, 0x20, 0xb6,
	0xed, 0x69, 0x7c, 0xde, 0x13, 0x98, 0x44, 0xd2, 0xaf, 0x8b, 0x4a, 0x38, 0x7f, 0xcf, 0xb5, 0x2b,
	0xf9, 0xbc, 0xe7, 0xf5, 0xd5, 0x4d, 0xfe, 0xdb, 0x9f, 0x04, 0x7c, 0x87, 0x41, 0x84, 0x69, 0xc9,
	0x0a, 0x6e, 0x7b, 0xf8, 0x89, 0xfd, 0x8d, 0x14, 0x6e, 0x5f, 0xf2, 0x5a, 0x09, 0x79, 0xa0, 0xf9,
	0xc9, 0x31, 0x1c, 0xb2, 0x70, 0x0e, 0x33, 0xa5, 0x99, 0xde, 0x2b, 0x3a, 0xb5, 0x6f, 0x4d, 0x64,
	0x08, 0xdf, 0x44, 0xce, 0x3f, 0xbc, 0x51, 0xf4, 0x56, 0x38, 0x31, 0x84, 0x26, 0xc4, 0x47, 0x00,
	0x29, 0xd3, 0x4c, 0x71, 0x6d, 0x92, 0x33, 0x9b, 0xec, 0xbc, 0x44, 0x02, 0x82, 0xde, 0xb4, 0x0c,
	0x6a, 0x27, 0x4b, 0xcd, 0x4b, 0xdd, 0x78, 0x3c, 0x86, 0xce, 0xba, 0xd7, 0xb1, 0xbe, 0x80, 0x3b,
	0xa6, 0x93, 0xbe, 0xaa, 0x78, 0x63, 0xd3, 0xc5, 0x8d, 0xf9, 0xa9, 0x1b, 0xc4, 0x57, 0xb8, 0x68,
	0xb7, 0xec, 0x30, 0xae, 0xb7, 0x97, 0x06, 0xfc, 0x4f, 0xc3, 0x3f, 0x50, 0x3d, 0x47, 0xdd, 0x00,
	0x7e, 0xdc, 0xe7, 0x5a, 0x54, 0x79, 0xbb, 0xc3, 0x0a, 0x9f, 0x00, 0x38, 0x89, 0xa2, 0x24, 0x9c,
	0x8c, 0x99, 0x9d, 0x82, 0xf8, 0x37, 0x01, 0x74, 0x99, 0x75, 0x96, 0xd5, 0x3c, 0x63, 0x9a, 0xe3,
	0x6b, 0x38, 0x1b, 0x5c, 0x07, 0x2e, 0x0c, 0xe4, 0xfa, 0x93, 0x59, 0xf4, 0x1b, 0x44, 0x27, 0xf8,
	0x1c, 0xee, 0x76, 0x57, 0x0d, 0x2f, 0x4c, 0xc1, 0x68, 0xf9, 0xc6, 0xba, 0x57, 0x10, 0xf4, 0x0e,
	0x04, 0xa9, 0xad, 0xb8, 0xe6, 0x66, 0x46, 0xda, 0xf8, 0x17, 0x81, 0xfb, 0x7d, 0xfe, 0x17, 0x2d,
	0x6b, 0x8e, 0xab, 0x81, 0x97, 0xbe, 0x70, 0xec, 0xe1, 0x25, 0x04, 0xdd, 0x7a, 0x35, 0x14, 0xcc,
	0x4d, 0x38, 0x9e, 0x7c, 0x74, 0x82, 0x4f, 0xc7, 0x53, 0xfb, 0x4b, 0xb3, 0xed, 0xcc, 0x7e, 0x91,
	0x9e, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x2b, 0x8c, 0x32, 0xa4, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AlgorithmAggregateClient is the client API for AlgorithmAggregate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlgorithmAggregateClient interface {
	CreateAlgorithm(ctx context.Context, in *CreateAlgorithmCommand, opts ...grpc.CallOption) (*Algorithm, error)
	GetAlgorithm(ctx context.Context, in *GetAlgorithmQuery, opts ...grpc.CallOption) (*Algorithm, error)
	AssociateFile(ctx context.Context, in *AssociateFileCommand, opts ...grpc.CallOption) (*Algorithm, error)
}

type algorithmAggregateClient struct {
	cc *grpc.ClientConn
}

func NewAlgorithmAggregateClient(cc *grpc.ClientConn) AlgorithmAggregateClient {
	return &algorithmAggregateClient{cc}
}

func (c *algorithmAggregateClient) CreateAlgorithm(ctx context.Context, in *CreateAlgorithmCommand, opts ...grpc.CallOption) (*Algorithm, error) {
	out := new(Algorithm)
	err := c.cc.Invoke(ctx, "/pb.AlgorithmAggregate/CreateAlgorithm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorithmAggregateClient) GetAlgorithm(ctx context.Context, in *GetAlgorithmQuery, opts ...grpc.CallOption) (*Algorithm, error) {
	out := new(Algorithm)
	err := c.cc.Invoke(ctx, "/pb.AlgorithmAggregate/GetAlgorithm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorithmAggregateClient) AssociateFile(ctx context.Context, in *AssociateFileCommand, opts ...grpc.CallOption) (*Algorithm, error) {
	out := new(Algorithm)
	err := c.cc.Invoke(ctx, "/pb.AlgorithmAggregate/AssociateFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlgorithmAggregateServer is the server API for AlgorithmAggregate service.
type AlgorithmAggregateServer interface {
	CreateAlgorithm(context.Context, *CreateAlgorithmCommand) (*Algorithm, error)
	GetAlgorithm(context.Context, *GetAlgorithmQuery) (*Algorithm, error)
	AssociateFile(context.Context, *AssociateFileCommand) (*Algorithm, error)
}

func RegisterAlgorithmAggregateServer(s *grpc.Server, srv AlgorithmAggregateServer) {
	s.RegisterService(&_AlgorithmAggregate_serviceDesc, srv)
}

func _AlgorithmAggregate_CreateAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlgorithmCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmAggregateServer).CreateAlgorithm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AlgorithmAggregate/CreateAlgorithm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmAggregateServer).CreateAlgorithm(ctx, req.(*CreateAlgorithmCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlgorithmAggregate_GetAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlgorithmQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmAggregateServer).GetAlgorithm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AlgorithmAggregate/GetAlgorithm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmAggregateServer).GetAlgorithm(ctx, req.(*GetAlgorithmQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlgorithmAggregate_AssociateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssociateFileCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmAggregateServer).AssociateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AlgorithmAggregate/AssociateFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmAggregateServer).AssociateFile(ctx, req.(*AssociateFileCommand))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlgorithmAggregate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AlgorithmAggregate",
	HandlerType: (*AlgorithmAggregateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlgorithm",
			Handler:    _AlgorithmAggregate_CreateAlgorithm_Handler,
		},
		{
			MethodName: "GetAlgorithm",
			Handler:    _AlgorithmAggregate_GetAlgorithm_Handler,
		},
		{
			MethodName: "AssociateFile",
			Handler:    _AlgorithmAggregate_AssociateFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "algorithm.proto",
}

// AlgorithmQueryStoreClient is the client API for AlgorithmQueryStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlgorithmQueryStoreClient interface {
	GetAlgorithm(ctx context.Context, in *Algorithm, opts ...grpc.CallOption) (*Algorithm, error)
	GetAlgorithms(ctx context.Context, in *Algorithm, opts ...grpc.CallOption) (*MultipleAlgorithms, error)
	CreateAlgorithm(ctx context.Context, in *Algorithm, opts ...grpc.CallOption) (*Algorithm, error)
}

type algorithmQueryStoreClient struct {
	cc *grpc.ClientConn
}

func NewAlgorithmQueryStoreClient(cc *grpc.ClientConn) AlgorithmQueryStoreClient {
	return &algorithmQueryStoreClient{cc}
}

func (c *algorithmQueryStoreClient) GetAlgorithm(ctx context.Context, in *Algorithm, opts ...grpc.CallOption) (*Algorithm, error) {
	out := new(Algorithm)
	err := c.cc.Invoke(ctx, "/pb.AlgorithmQueryStore/GetAlgorithm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorithmQueryStoreClient) GetAlgorithms(ctx context.Context, in *Algorithm, opts ...grpc.CallOption) (*MultipleAlgorithms, error) {
	out := new(MultipleAlgorithms)
	err := c.cc.Invoke(ctx, "/pb.AlgorithmQueryStore/GetAlgorithms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorithmQueryStoreClient) CreateAlgorithm(ctx context.Context, in *Algorithm, opts ...grpc.CallOption) (*Algorithm, error) {
	out := new(Algorithm)
	err := c.cc.Invoke(ctx, "/pb.AlgorithmQueryStore/CreateAlgorithm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlgorithmQueryStoreServer is the server API for AlgorithmQueryStore service.
type AlgorithmQueryStoreServer interface {
	GetAlgorithm(context.Context, *Algorithm) (*Algorithm, error)
	GetAlgorithms(context.Context, *Algorithm) (*MultipleAlgorithms, error)
	CreateAlgorithm(context.Context, *Algorithm) (*Algorithm, error)
}

func RegisterAlgorithmQueryStoreServer(s *grpc.Server, srv AlgorithmQueryStoreServer) {
	s.RegisterService(&_AlgorithmQueryStore_serviceDesc, srv)
}

func _AlgorithmQueryStore_GetAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Algorithm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmQueryStoreServer).GetAlgorithm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AlgorithmQueryStore/GetAlgorithm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmQueryStoreServer).GetAlgorithm(ctx, req.(*Algorithm))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlgorithmQueryStore_GetAlgorithms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Algorithm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmQueryStoreServer).GetAlgorithms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AlgorithmQueryStore/GetAlgorithms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmQueryStoreServer).GetAlgorithms(ctx, req.(*Algorithm))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlgorithmQueryStore_CreateAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Algorithm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmQueryStoreServer).CreateAlgorithm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AlgorithmQueryStore/CreateAlgorithm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmQueryStoreServer).CreateAlgorithm(ctx, req.(*Algorithm))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlgorithmQueryStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AlgorithmQueryStore",
	HandlerType: (*AlgorithmQueryStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAlgorithm",
			Handler:    _AlgorithmQueryStore_GetAlgorithm_Handler,
		},
		{
			MethodName: "GetAlgorithms",
			Handler:    _AlgorithmQueryStore_GetAlgorithms_Handler,
		},
		{
			MethodName: "CreateAlgorithm",
			Handler:    _AlgorithmQueryStore_CreateAlgorithm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "algorithm.proto",
}
