// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventstore.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventFilter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventFilter) Reset()         { *m = EventFilter{} }
func (m *EventFilter) String() string { return proto.CompactTextString(m) }
func (*EventFilter) ProtoMessage()    {}
func (*EventFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{0}
}

func (m *EventFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventFilter.Unmarshal(m, b)
}
func (m *EventFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventFilter.Marshal(b, m, deterministic)
}
func (m *EventFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventFilter.Merge(m, src)
}
func (m *EventFilter) XXX_Size() int {
	return xxx_messageInfo_EventFilter.Size(m)
}
func (m *EventFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_EventFilter.DiscardUnknown(m)
}

var xxx_messageInfo_EventFilter proto.InternalMessageInfo

type EventResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResponse) Reset()         { *m = EventResponse{} }
func (m *EventResponse) String() string { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()    {}
func (*EventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{1}
}

func (m *EventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponse.Unmarshal(m, b)
}
func (m *EventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponse.Marshal(b, m, deterministic)
}
func (m *EventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponse.Merge(m, src)
}
func (m *EventResponse) XXX_Size() int {
	return xxx_messageInfo_EventResponse.Size(m)
}
func (m *EventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponse proto.InternalMessageInfo

func (m *EventResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	EventId              string   `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType            string   `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AggregateId          string   `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateType        string   `protobuf:"bytes,4,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	EventData            string   `protobuf:"bytes,5,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	Channel              string   `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{2}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Event) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *Event) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func (m *Event) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

func (m *Event) GetEventData() string {
	if m != nil {
		return m.EventData
	}
	return ""
}

func (m *Event) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type Response struct {
	IsSuccessful         bool     `protobuf:"varint,1,opt,name=is_successful,json=isSuccessful,proto3" json:"is_successful,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetIsSuccessful() bool {
	if m != nil {
		return m.IsSuccessful
	}
	return false
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*EventFilter)(nil), "pb.EventFilter")
	proto.RegisterType((*EventResponse)(nil), "pb.EventResponse")
	proto.RegisterType((*Event)(nil), "pb.Event")
	proto.RegisterType((*Response)(nil), "pb.Response")
}

func init() { proto.RegisterFile("eventstore.proto", fileDescriptor_00783576c07562d6) }

var fileDescriptor_00783576c07562d6 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x51, 0x4f, 0x83, 0x30,
	0x14, 0x85, 0x65, 0x73, 0x0c, 0x2e, 0x60, 0x4c, 0xe3, 0x43, 0x35, 0x31, 0x99, 0x18, 0x13, 0x9e,
	0x78, 0xc0, 0xc4, 0x3f, 0xa0, 0x33, 0xd9, 0x2b, 0xf3, 0x7d, 0x29, 0x70, 0x45, 0x12, 0x02, 0x4d,
	0xdb, 0x99, 0xec, 0xff, 0xf9, 0xc3, 0x0c, 0xb7, 0xd8, 0xf9, 0xc6, 0xf9, 0xee, 0x69, 0x0f, 0xf7,
	0x14, 0xae, 0xf1, 0x1b, 0x07, 0xa3, 0xcd, 0xa8, 0x30, 0x97, 0x6a, 0x34, 0x23, 0x5b, 0xc8, 0x2a,
	0x4d, 0x20, 0xda, 0x4e, 0xfc, 0xbd, 0xeb, 0x0d, 0xaa, 0xb4, 0x80, 0x84, 0x64, 0x89, 0x5a, 0x8e,
	0x83, 0x46, 0xf6, 0x00, 0xbe, 0x3d, 0xc7, 0xbd, 0xcd, 0x32, 0x8b, 0x8a, 0x30, 0x97, 0x55, 0x6e,
	0x2d, 0xf3, 0x20, 0xfd, 0xf1, 0x60, 0x45, 0x84, 0xdd, 0x42, 0x40, 0xec, 0xd0, 0x35, 0xdc, 0xdb,
	0x78, 0x59, 0x58, 0xae, 0x49, 0xef, 0x1a, 0x76, 0x0f, 0x60, 0x47, 0xe6, 0x24, 0x91, 0x2f, 0x68,
	0x18, 0x12, 0xf9, 0x38, 0xc9, 0x29, 0x26, 0x16, 0x6d, 0xab, 0xb0, 0x15, 0x06, 0xa7, 0xd3, 0x4b,
	0x32, 0x44, 0x8e, 0xed, 0x1a, 0xf6, 0x04, 0x57, 0x67, 0x0b, 0xdd, 0x72, 0x49, 0xa6, 0xc4, 0x51,
	0xba, 0xc9, 0x05, 0x35, 0xc2, 0x08, 0xbe, 0xfa, 0x17, 0xf4, 0x26, 0x8c, 0x60, 0x1c, 0xd6, 0xf5,
	0x97, 0x18, 0x06, 0xec, 0xb9, 0x6f, 0xff, 0x70, 0x96, 0xe9, 0x16, 0x02, 0xb7, 0xf5, 0x23, 0x24,
	0x9d, 0x3e, 0xe8, 0x63, 0x5d, 0xa3, 0xd6, 0x9f, 0xc7, 0x9e, 0xb6, 0x09, 0xca, 0xb8, 0xd3, 0x7b,
	0xc7, 0xd8, 0x0d, 0xac, 0x50, 0xa9, 0x51, 0xcd, 0xdb, 0x58, 0x51, 0xbc, 0x00, 0x50, 0x19, 0xfb,
	0xa9, 0x68, 0x96, 0x41, 0xf4, 0xaa, 0x50, 0x18, 0xb4, 0x05, 0x9d, 0xdb, 0xbb, 0x8b, 0xa7, 0xcf,
	0xbf, 0xc0, 0xf4, 0xa2, 0xf2, 0xe9, 0x4d, 0x9e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xec, 0xec,
	0xad, 0x71, 0xa7, 0x01, 0x00, 0x00,
}
